### ISSUE TITLE
Your email regex is flawed.

### ISSUE THREAD

**Issue by RandalSchwartz** [hello-addweb/email_validator#1]
No, please don't use this regex to validate email.  It's wrong.  The shortest regex to validate an RFC822 email address is about 2400 characters, and is given in https://www.ex-parrot.com/pdw/Mail-RFC822-Address.html.  Anything shorter is WRONG, unless you're using a grammar, as package:email_validator properly does.  Use that for Dart/Flutter please.

**Comment by sultan-addweb** [comment]
Done
